main: com.plugin.ColorSplat.Main
config: config
name: ColorSplat
version: 0.1
api-version: '1.17'

#All Commands
commands:
  startsplat:
    description: 'Starts the Color Splat Game'
    usage: '/<command>'
    permssion: ColorSplat.start
  endSplat:
    description: 'Ends the Color Splat Game'
    usage: '/<command>'
    permssion: ColorSplat.end